<?php
namespace App\Model\Table;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class CategoriesTable extends Table {
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->setTable('categories');
        $this->hasMany('Books', [
            'foreignKey' => 'category_id'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator->notEmptyString('name');

        return $validator;
    }
}
