<?php
namespace App\Model\Table;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class UsersTable extends Table {
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->setTable('users');

        $this->belongsTo('Groups', [
            'foreignKey' => 'group_id'
        ]);

        $this->hasMany('Comments', [
            'foreignKey' => 'user_id'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator->notEmptyString('username');
        $validator->notEmptyString('email');
        $validator->notEmptyString('password');
        $validator->notEmptyString('address');
        $validator->notEmptyString('phone');

        return $validator;
    }
}
