<?php
namespace App\Model\Table;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class WritersTable extends Table {
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->setTable('writers');

        $this->belongsToMany('Books', [
            'foreignKey' => 'writer_id',
            'targetForeignKey' => 'book_id',
            'joinTable' => 'books_writers'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator->notEmptyString('name');

        return $validator;
    }
}
